#!/usr/bin/env bash
set -euo pipefail

PROJECT_ID="${PROJECT_ID:-gopark-3da8f}"
REGION="${REGION:-us-central1}"
SERVICE_NAME="${SERVICE_NAME:-gopark-outbox-worker}"
DEPLOY_ENV="${DEPLOY_ENV:-production}"
AUTH_TOKEN_SECRET_NAME="${AUTH_TOKEN_SECRET_NAME:-gopark-auth-token-secret}"
DATABASE_URL_SECRET_NAME="${DATABASE_URL_SECRET_NAME:-gopark-database-url}"
REDIS_URL_SECRET_NAME="${REDIS_URL_SECRET_NAME:-gopark-redis-url}"
CLOUDSQL_INSTANCE="${CLOUDSQL_INSTANCE:-gopark-3da8f:us-central1:gopark-postgres}"
VPC_CONNECTOR="${VPC_CONNECTOR:-gopark-serverless-vpc}"
VPC_EGRESS="${VPC_EGRESS:-private-ranges-only}"
MIN_INSTANCES="${MIN_INSTANCES:-1}"
MAX_INSTANCES="${MAX_INSTANCES:-1}"
MEMORY="${MEMORY:-512Mi}"
CPU="${CPU:-1}"

PROJECT_ID="${PROJECT_ID}" \
REGION="${REGION}" \
SERVICE_NAME="${SERVICE_NAME}" \
DEPLOY_ENV="${DEPLOY_ENV}" \
APP_RUNTIME="worker" \
ALLOW_UNAUTHENTICATED="false" \
ALLOW_INSECURE_BOOTSTRAP_AUTH="false" \
AUTH_TOKEN_SECRET_NAME="${AUTH_TOKEN_SECRET_NAME}" \
DATABASE_URL_SECRET_NAME="${DATABASE_URL_SECRET_NAME}" \
REDIS_URL_SECRET_NAME="${REDIS_URL_SECRET_NAME}" \
CLOUDSQL_INSTANCE="${CLOUDSQL_INSTANCE}" \
VPC_CONNECTOR="${VPC_CONNECTOR}" \
VPC_EGRESS="${VPC_EGRESS}" \
MIN_INSTANCES="${MIN_INSTANCES}" \
MAX_INSTANCES="${MAX_INSTANCES}" \
MEMORY="${MEMORY}" \
CPU="${CPU}" \
NO_CPU_THROTTLING="true" \
bash "$(dirname "$0")/deploy_api_cloud_run.sh"
